export class BluePhoton extends Entity {
  constructor(position: Vector3) {
    super()
    engine.addEntity(this)
    this.addComponent(new Transform({ position: position}))
    this.addComponent(new GLTFShape("models/particle1.glb"))
  }
}


// const ball002 = new Entity()
// ball002.addComponent(new Transform())
// ball002.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball002)
// const ball003 = new Entity()
// ball003.addComponent(new Transform())
// ball003.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball003)
// const ball004 = new Entity()
// ball004.addComponent(new Transform())
// ball004.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball004)
// const ball005 = new Entity()
// ball005.addComponent(new Transform())
// ball005.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball005)
// const ball006 = new Entity()
// ball006.addComponent(new Transform())
// ball006.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball006)
// const ball007 = new Entity()
// ball007.addComponent(new Transform())
// ball007.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball007)
// const ball008 = new Entity()
// ball008.addComponent(new Transform())
// ball008.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball008)
// const ball009 = new Entity()
// ball009.addComponent(new Transform())
// ball009.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball009)
// const ball010 = new Entity()
// ball010.addComponent(new Transform())
// ball010.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball010)
// const ball011 = new Entity()
// ball011.addComponent(new Transform())
// ball011.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball011)
// const ball012 = new Entity()
// ball012.addComponent(new Transform())
// ball012.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball012)
// const ball013 = new Entity()
// ball013.addComponent(new Transform())
// ball013.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball013)
// const ball014 = new Entity()
// ball014.addComponent(new Transform())
// ball014.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball014)
// const ball015 = new Entity()
// ball015.addComponent(new Transform())
// ball015.addComponent(new GLTFShape("models/particle1.glb"))
// engine.addEntity(ball015)